// <auto-generated />
using System;
using InspireMind.Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InspireMind.Education.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240820100647_Seed20NewCourses")]
    partial class Seed20NewCourses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed9aafb1-872d-48a9-ade2-1a37b3a39f56"),
                            CourseName = "C# Basics",
                            Duration = 30,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("4976c9f0-c558-41bf-be86-190249fac48d"),
                            CourseName = "Advanced C#",
                            Duration = 40,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("34f1d3b2-5e90-4873-a5c8-f9a3ae175b3b"),
                            CourseName = "JavaScript Essentials",
                            Duration = 25,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("4996138f-fd12-4126-9e29-6bbf7e0330bf"),
                            CourseName = "React Fundamentals",
                            Duration = 35,
                            TopicId = new Guid("b16ea527-9f9c-4c58-8385-a2f69e5c83d9")
                        },
                        new
                        {
                            Id = new Guid("0bca523a-285d-48fd-a805-7950f6bf676f"),
                            CourseName = "TypeScript for Beginners",
                            Duration = 20,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("375a26a9-a1ed-42e2-95e7-e9a30824d192"),
                            CourseName = "Python Programming",
                            Duration = 45,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("102f8148-fcf8-4c1f-b513-21327622b8e1"),
                            CourseName = "Java Programming",
                            Duration = 50,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("5661c5b1-3fc1-4b84-99f5-898c6679fdf2"),
                            CourseName = "SQL Basics",
                            Duration = 30,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("83c47415-c606-4cf5-a13f-d692e7326edd"),
                            CourseName = "NoSQL Databases",
                            Duration = 40,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("99eedb49-b4f1-4c13-a3ce-80059ab6f559"),
                            CourseName = "Data Structures",
                            Duration = 35,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("808ca6a1-258e-4077-a443-af979e010d73"),
                            CourseName = "Algorithms",
                            Duration = 40,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("f8475a7e-7778-4ddf-8bf7-6879da2e2e02"),
                            CourseName = "Web Development",
                            Duration = 50,
                            TopicId = new Guid("b16ea527-9f9c-4c58-8385-a2f69e5c83d9")
                        },
                        new
                        {
                            Id = new Guid("e99c06c9-8605-4136-9c40-556bfd9ee2a2"),
                            CourseName = "Mobile App Development",
                            Duration = 45,
                            TopicId = new Guid("b9dd9a87-4852-434e-99dd-3103f7fba183")
                        },
                        new
                        {
                            Id = new Guid("6bae2c61-0dd3-44e4-8c0c-e98add7f3948"),
                            CourseName = "Cloud Computing",
                            Duration = 30,
                            TopicId = new Guid("7db2ed45-a087-4e00-b804-b944f400f450")
                        },
                        new
                        {
                            Id = new Guid("7496625c-9fad-4a07-87c6-98ba31c0064f"),
                            CourseName = "DevOps Practices",
                            Duration = 35,
                            TopicId = new Guid("7db2ed45-a087-4e00-b804-b944f400f450")
                        },
                        new
                        {
                            Id = new Guid("bf1dcec8-b9fe-40f0-b847-2a142fc320f3"),
                            CourseName = "Cybersecurity Basics",
                            Duration = 25,
                            TopicId = new Guid("62841cba-863b-4816-9366-e789646ca43e")
                        },
                        new
                        {
                            Id = new Guid("1e2bac13-26be-4ff0-9716-ea95970a7bb7"),
                            CourseName = "Machine Learning",
                            Duration = 50,
                            TopicId = new Guid("71fd7466-e4d4-41f6-ace8-ed67ea8fafcf")
                        },
                        new
                        {
                            Id = new Guid("aa25d7c5-5f48-40b3-be6e-4bf6eb577f7a"),
                            CourseName = "Artificial Intelligence",
                            Duration = 55,
                            TopicId = new Guid("71fd7466-e4d4-41f6-ace8-ed67ea8fafcf")
                        },
                        new
                        {
                            Id = new Guid("a4207bab-0908-4ff5-878c-0ae69dba6457"),
                            CourseName = "Blockchain Technology",
                            Duration = 40,
                            TopicId = new Guid("df8d86f9-69d9-4eda-9fc4-aa8725c7a47b")
                        },
                        new
                        {
                            Id = new Guid("1ab8063b-dc0f-43a6-9109-ed1b6770c82d"),
                            CourseName = "Internet of Things (IoT)",
                            Duration = 35,
                            TopicId = new Guid("5393a6fe-5c8b-42af-a453-2af2c64f5a35")
                        },
                        new
                        {
                            Id = new Guid("a0a38f9a-8d3c-4f88-9092-48d0eb7764b3"),
                            CourseName = "Kotlin for Android Development",
                            Duration = 40,
                            TopicId = new Guid("b9dd9a87-4852-434e-99dd-3103f7fba183")
                        },
                        new
                        {
                            Id = new Guid("7a5f4a5a-b46e-41a3-8e68-00b378b0e7db"),
                            CourseName = "Swift Programming",
                            Duration = 35,
                            TopicId = new Guid("b9dd9a87-4852-434e-99dd-3103f7fba183")
                        },
                        new
                        {
                            Id = new Guid("f6f5d3eb-db8b-4e99-b0df-9afc4b7f1c48"),
                            CourseName = "Ruby on Rails",
                            Duration = 45,
                            TopicId = new Guid("b16ea527-9f9c-4c58-8385-a2f69e5c83d9")
                        },
                        new
                        {
                            Id = new Guid("acee13c3-c20c-4b4c-ad19-4a4d9868424d"),
                            CourseName = "PHP for Web Development",
                            Duration = 30,
                            TopicId = new Guid("b16ea527-9f9c-4c58-8385-a2f69e5c83d9")
                        },
                        new
                        {
                            Id = new Guid("88b07cb4-74ec-4d79-9e77-b0fbbc7f914c"),
                            CourseName = "Angular Development",
                            Duration = 40,
                            TopicId = new Guid("b16ea527-9f9c-4c58-8385-a2f69e5c83d9")
                        },
                        new
                        {
                            Id = new Guid("fc563f61-c90d-4f1a-9e5b-8c9efdf59323"),
                            CourseName = "Vue.js Fundamentals",
                            Duration = 35,
                            TopicId = new Guid("b16ea527-9f9c-4c58-8385-a2f69e5c83d9")
                        },
                        new
                        {
                            Id = new Guid("9b7d74e9-a0a7-4d6c-a27e-7f6eed4ba1cb"),
                            CourseName = "Golang Programming",
                            Duration = 45,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("30fe5c0c-7db5-4f7c-b3a4-21711b3a36b7"),
                            CourseName = "Rust for Systems Programming",
                            Duration = 50,
                            TopicId = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563")
                        },
                        new
                        {
                            Id = new Guid("3b28dfaa-03b3-4382-a1a9-3c8c8fe5682b"),
                            CourseName = "Docker & Kubernetes",
                            Duration = 40,
                            TopicId = new Guid("7db2ed45-a087-4e00-b804-b944f400f450")
                        },
                        new
                        {
                            Id = new Guid("ace2bce9-6c9d-47f8-995d-6d8bca51d5c2"),
                            CourseName = "AWS Cloud Practitioner",
                            Duration = 35,
                            TopicId = new Guid("7db2ed45-a087-4e00-b804-b944f400f450")
                        },
                        new
                        {
                            Id = new Guid("0b873a94-4b77-4c08-b7a4-6f3b816d0e91"),
                            CourseName = "Azure Fundamentals",
                            Duration = 30,
                            TopicId = new Guid("7db2ed45-a087-4e00-b804-b944f400f450")
                        },
                        new
                        {
                            Id = new Guid("16daf9cb-a94e-4c3e-8a84-47fb0cf5917d"),
                            CourseName = "Google Cloud Platform Essentials",
                            Duration = 35,
                            TopicId = new Guid("7db2ed45-a087-4e00-b804-b944f400f450")
                        },
                        new
                        {
                            Id = new Guid("9ac899b5-9e60-4d44-b202-8fdc85cfb77c"),
                            CourseName = "Big Data with Hadoop",
                            Duration = 50,
                            TopicId = new Guid("71fd7466-e4d4-41f6-ace8-ed67ea8fafcf")
                        },
                        new
                        {
                            Id = new Guid("a318f207-098d-46b9-bb8d-5b96b3a04d35"),
                            CourseName = "Data Visualization with Tableau",
                            Duration = 25,
                            TopicId = new Guid("71fd7466-e4d4-41f6-ace8-ed67ea8fafcf")
                        },
                        new
                        {
                            Id = new Guid("db63e2d8-7fec-4f79-bc1e-50c6728192c3"),
                            CourseName = "Ethical Hacking",
                            Duration = 45,
                            TopicId = new Guid("62841cba-863b-4816-9366-e789646ca43e")
                        },
                        new
                        {
                            Id = new Guid("6cff4994-907a-46aa-8fc7-3e5976c5b4a1"),
                            CourseName = "Penetration Testing",
                            Duration = 40,
                            TopicId = new Guid("62841cba-863b-4816-9366-e789646ca43e")
                        },
                        new
                        {
                            Id = new Guid("d8496fc3-8e36-4c99-875d-53d7c2e156d2"),
                            CourseName = "Artificial Neural Networks",
                            Duration = 50,
                            TopicId = new Guid("71fd7466-e4d4-41f6-ace8-ed67ea8fafcf")
                        },
                        new
                        {
                            Id = new Guid("7559534a-0c8b-4e2a-85f8-ffcbf3d16a1e"),
                            CourseName = "Natural Language Processing",
                            Duration = 55,
                            TopicId = new Guid("71fd7466-e4d4-41f6-ace8-ed67ea8fafcf")
                        },
                        new
                        {
                            Id = new Guid("902bfb23-70a0-4a55-b8c0-432cea6f7d1c"),
                            CourseName = "Augmented Reality Development",
                            Duration = 45,
                            TopicId = new Guid("b9dd9a87-4852-434e-99dd-3103f7fba183")
                        },
                        new
                        {
                            Id = new Guid("deea5689-78c2-42b4-a287-52e66394a219"),
                            CourseName = "Virtual Reality Development",
                            Duration = 45,
                            TopicId = new Guid("b9dd9a87-4852-434e-99dd-3103f7fba183")
                        });
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<Guid?>("InstructorManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<DateOnly?>("ManageDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorManagerId")
                        .IsUnique()
                        .HasFilter("[InstructorManagerId] IS NOT NULL");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors", (string)null);
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.InstructorCourse", b =>
                {
                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InstructorId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("InstructorCourses", (string)null);
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.StudentCourse", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentCourses", (string)null);
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Topics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b0418c2-d8c8-46fb-bd0d-0094f83ad563"),
                            TopicName = "Programming"
                        },
                        new
                        {
                            Id = new Guid("b16ea527-9f9c-4c58-8385-a2f69e5c83d9"),
                            TopicName = "Web Development"
                        },
                        new
                        {
                            Id = new Guid("b9dd9a87-4852-434e-99dd-3103f7fba183"),
                            TopicName = "Mobile App Development"
                        },
                        new
                        {
                            Id = new Guid("7db2ed45-a087-4e00-b804-b944f400f450"),
                            TopicName = "Cloud Computing"
                        },
                        new
                        {
                            Id = new Guid("b8c0db6a-716d-4004-9c89-0e7cf1ba790c"),
                            TopicName = "DevOps Practices"
                        },
                        new
                        {
                            Id = new Guid("62841cba-863b-4816-9366-e789646ca43e"),
                            TopicName = "Cybersecurity"
                        },
                        new
                        {
                            Id = new Guid("096acc69-09a4-4f36-84ff-322e9846ad54"),
                            TopicName = "Machine Learning"
                        },
                        new
                        {
                            Id = new Guid("71fd7466-e4d4-41f6-ace8-ed67ea8fafcf"),
                            TopicName = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("df8d86f9-69d9-4eda-9fc4-aa8725c7a47b"),
                            TopicName = "Blockchain Technology"
                        },
                        new
                        {
                            Id = new Guid("5393a6fe-5c8b-42af-a453-2af2c64f5a35"),
                            TopicName = "Internet of Things (IoT)"
                        });
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Course", b =>
                {
                    b.HasOne("InspireMind.Education.Domain.Entities.Topic", "Topic")
                        .WithMany("Courses")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Department", b =>
                {
                    b.HasOne("InspireMind.Education.Domain.Entities.Instructor", "InstructorManager")
                        .WithOne()
                        .HasForeignKey("InspireMind.Education.Domain.Entities.Department", "InstructorManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("InstructorManager");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Instructor", b =>
                {
                    b.HasOne("InspireMind.Education.Domain.Entities.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.InstructorCourse", b =>
                {
                    b.HasOne("InspireMind.Education.Domain.Entities.Course", "Course")
                        .WithMany("InstructorCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspireMind.Education.Domain.Entities.Instructor", "Instructor")
                        .WithMany("InstructorCourses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Student", b =>
                {
                    b.HasOne("InspireMind.Education.Domain.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.StudentCourse", b =>
                {
                    b.HasOne("InspireMind.Education.Domain.Entities.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InspireMind.Education.Domain.Entities.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Course", b =>
                {
                    b.Navigation("InstructorCourses");

                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Instructor", b =>
                {
                    b.Navigation("InstructorCourses");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentCourses");
                });

            modelBuilder.Entity("InspireMind.Education.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
